In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data/cancer_detection_ml_practice_1000.csv")
df.head()

,Patient_ID,Hospital_ID,Patient_Age,Contact_Number,Salary,BMI,Exercise_Time,Any_Existing_Disease,CheckUp_Date,Alcohol,Cancer_Detected
0,P10001,H007,50,9235661445,135235,30.0,16,No,2025-04-08,No,No
1,P10002,H004,64,9507062536,233971,33.8,5,No,2025-01-18,No,No
2,P10003,H008,57,9899775493,196773,19.5,18,Yes,2023-07-15,No,No
3,P10004,H005,77,9600812872,126777,27.2,55,No,2022-10-21,Yes,No
4,P10005,H007,60,9323214950,37033,22.9,101,No,2024-07-07,Yes,No

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["Cancer"] = encoder.fit_transform(df["Cancer_Detected"])
df["Is_Alcohol"] = encoder.fit_transform(df["Alcohol"])
df["Is_Existing_Disease"] = encoder.fit_transform(df["Any_Existing_Disease"])

In [5]:
df.head()

,Patient_ID,Hospital_ID,Patient_Age,Contact_Number,Salary,BMI,Exercise_Time,Any_Existing_Disease,CheckUp_Date,Alcohol,Cancer_Detected,Cancer,Is_Alcohol,Is_Existing_Disease
0,P10001,H007,50,9235661445,135235,30.0,16,No,2025-04-08,No,No,0,0,0
1,P10002,H004,64,9507062536,233971,33.8,5,No,2025-01-18,No,No,0,0,0
2,P10003,H008,57,9899775493,196773,19.5,18,Yes,2023-07-15,No,No,0,0,1
3,P10004,H005,77,9600812872,126777,27.2,55,No,2022-10-21,Yes,No,0,1,0
4,P10005,H007,60,9323214950,37033,22.9,101,No,2024-07-07,Yes,No,0,1,0